# on myown vds
#
#             .-/+oossssoo+/-.               likeuser@machine
#         `:+ssssssssssssssssss+:`           ----------------
#       -+ssssssssssssssssssyyssss+-         OS: Ubuntu 24.04.2 LTS x86_64
#     .ossssssssssssssssssdMMMNysssso.       Host: Virtual Machine Hyper-V UEFI Release v4.1
#    /ssssssssssshdmmNNmmyNMMMMhssssss/      Kernel: 6.11.0-1014-azure
#   +ssssssssshmydMMMMMMMNddddyssssssss+     Uptime: 16 mins
#  /sssssssshNMMMyhhyyyyhmNMMMNhssssssss/    Packages: 1324 (dpkg)
# .ssssssssdMMMNhsssssssssshNMMMdssssssss.   Shell: bash 5.2.21
# +sssshhhyNMMNyssssssssssssyNMMMysssssss+   Resolution: 1024x768
# ossyNMMMNyMMhsssssssssssssshmmmhssssssso   Terminal: /dev/pts/0
# ossyNMMMNyMMhsssssssssssssshmmmhssssssso   CPU: Intel Xeon Platinum 8370C (2) @ 2.800GHz
# +sssshhhyNMMNyssssssssssssyNMMMysssssss+   Memory: 451MiB / 15944MiB
# .ssssssssdMMMNhsssssssssshNMMMdssssssss.
#  /sssssssshNMMMyhhyyyyhdNMMMNhssssssss/
#   +sssssssssdmydMMMMMMMMddddyssssssss+
#    /ssssssssssshdmNNNNmyNMMMMhssssss/
#     .ossssssssssssssssssdMMMNysssso.
#       -+sssssssssssssssssyyyssss+-
#         `:+ssssssssssssssssss+:`
#             .-/+oossssoo+/-.
#

# likeuser@machine:~$ sudo docker ps
# CONTAINER ID   IMAGE         COMMAND                  CREATED         STATUS         PORTS                                         NAMES
# 729a26279a3a   postgres:15   "docker-entrypoint.s…"   5 seconds ago   Up 4 seconds   0.0.0.0:6543->5432/tcp, [::]:6543->5432/tcp   doom

version: '3.9'
services:
  postgres:
    image: postgres:15
    container_name: doom
    restart: always
    ports:
      - '6543:5432'
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: bro_dont_tell_this_to_anyone
      POSTGRES_DB: doom
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
